spring:
  datasource:
    url: jdbc:h2:file:./data/WelcomeDB
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    database: h2
  sql:
    init:
      platform: h2
      data-locations: data-test.sql

expirationtime: 60

secretkey: 4D18A3F7E9B1C6A025EDD6F82A1404425F00E9797B7DB30299811AC180995C14
