-- INSERT INTO City(name) VALUES ( 'Roma' );
-- INSERT INTO City(name) VALUES ( 'Milano' );
-- INSERT INTO City(name) VALUES ( 'Napoli' );
INSERT INTO City(name) VALUES ('Agrigento');
INSERT INTO City(name) VALUES ('Alessandria');
INSERT INTO City(name) VALUES ('Ancona');
INSERT INTO City(name) VALUES ('Aosta');
INSERT INTO City(name) VALUES ('Arezzo');
INSERT INTO City(name) VALUES ('Ascoli Piceno');
INSERT INTO City(name) VALUES ('Asti');
INSERT INTO City(name) VALUES ('Avellino');
INSERT INTO City(name) VALUES ('Bari');
INSERT INTO City(name) VALUES ('Barletta-Andria-Trani');
INSERT INTO City(name) VALUES ('Belluno');
INSERT INTO City(name) VALUES ('Benevento');
INSERT INTO City(name) VALUES ('Bergamo');
INSERT INTO City(name) VALUES ('Biella');
INSERT INTO City(name) VALUES ('Bologna');
INSERT INTO City(name) VALUES ('Bolzano');
INSERT INTO City(name) VALUES ('Brescia');
INSERT INTO City(name) VALUES ('Brindisi');
INSERT INTO City(name) VALUES ('Cagliari');
INSERT INTO City(name) VALUES ('Caltanissetta');
INSERT INTO City(name) VALUES ('Campobasso');
INSERT INTO City(name) VALUES ('Carbonia-Iglesias');
INSERT INTO City(name) VALUES ('Caserta');
INSERT INTO City(name) VALUES ('Catania');
INSERT INTO City(name) VALUES ('Catanzaro');
INSERT INTO City(name) VALUES ('Chieti');
INSERT INTO City(name) VALUES ('Como');
INSERT INTO City(name) VALUES ('Cosenza');
INSERT INTO City(name) VALUES ('Cremona');
INSERT INTO City(name) VALUES ('Crotone');
INSERT INTO City(name) VALUES ('Cuneo');
INSERT INTO City(name) VALUES ('Enna');
INSERT INTO City(name) VALUES ('Fermo');
INSERT INTO City(name) VALUES ('Ferrara');
INSERT INTO City(name) VALUES ('Firenze');
INSERT INTO City(name) VALUES ('Foggia');
INSERT INTO City(name) VALUES ('Forlì-Cesena');
INSERT INTO City(name) VALUES ('Frosinone');
INSERT INTO City(name) VALUES ('Genova');
INSERT INTO City(name) VALUES ('Gorizia');
INSERT INTO City(name) VALUES ('Grosseto');
INSERT INTO City(name) VALUES ('Imperia');
INSERT INTO City(name) VALUES ('Isernia');
INSERT INTO City(name) VALUES ('La Spezia');
INSERT INTO City(name) VALUES ('L Aquila');
INSERT INTO City(name) VALUES ('Latina');
INSERT INTO City(name) VALUES ('Lecce');
INSERT INTO City(name) VALUES ('Lecco');
INSERT INTO City(name) VALUES ('Livorno');
INSERT INTO City(name) VALUES ('Lodi');
INSERT INTO City(name) VALUES ('Lucca');
INSERT INTO City(name) VALUES ('Macerata');
INSERT INTO City(name) VALUES ('Mantova');
INSERT INTO City(name) VALUES ('Massa-Carrara');
INSERT INTO City(name) VALUES ('Matera');
INSERT INTO City(name) VALUES ('Messina');
INSERT INTO City(name) VALUES ('Milano');
INSERT INTO City(name) VALUES ('Modena');
INSERT INTO City(name) VALUES ('Monza e della Brianza');
INSERT INTO City(name) VALUES ('Napoli');
INSERT INTO City(name) VALUES ('Novara');
INSERT INTO City(name) VALUES ('Nuoro');
INSERT INTO City(name) VALUES ('Olbia-Tempio');
INSERT INTO City(name) VALUES ('Oristano');
INSERT INTO City(name) VALUES ('Padova');
INSERT INTO City(name) VALUES ('Palermo');
INSERT INTO City(name) VALUES ('Parma');
INSERT INTO City(name) VALUES ('Pavia');
INSERT INTO City(name) VALUES ('Perugia');
INSERT INTO City(name) VALUES ('Pesaro e Urbino');
INSERT INTO City(name) VALUES ('Pescara');
INSERT INTO City(name) VALUES ('Piacenza');
INSERT INTO City(name) VALUES ('Pisa');
INSERT INTO City(name) VALUES ('Pistoia');
INSERT INTO City(name) VALUES ('Pordenone');
INSERT INTO City(name) VALUES ('Potenza');
INSERT INTO City(name) VALUES ('Prato');
INSERT INTO City(name) VALUES ('Ragusa');
INSERT INTO City(name) VALUES ('Ravenna');
INSERT INTO City(name) VALUES ('Reggio Calabria');
INSERT INTO City(name) VALUES ('Reggio Emilia');
INSERT INTO City(name) VALUES ('Rieti');
INSERT INTO City(name) VALUES ('Rimini');
INSERT INTO City(name) VALUES ('Roma');
INSERT INTO City(name) VALUES ('Rovigo');
INSERT INTO City(name) VALUES ('Salerno');
INSERT INTO City(name) VALUES ('Medio Campidano');
INSERT INTO City(name) VALUES ('Sassari');
INSERT INTO City(name) VALUES ('Savona');
INSERT INTO City(name) VALUES ('Siena');
INSERT INTO City(name) VALUES ('Siracusa');
INSERT INTO City(name) VALUES ('Sondrio');
INSERT INTO City(name) VALUES ('Taranto');
INSERT INTO City(name) VALUES ('Teramo');
INSERT INTO City(name) VALUES ('Terni');
INSERT INTO City(name) VALUES ('Torino');
INSERT INTO City(name) VALUES ('Ogliastra');
INSERT INTO City(name) VALUES ('Trapani');
INSERT INTO City(name) VALUES ('Trento');
INSERT INTO City(name) VALUES ('Treviso');
INSERT INTO City(name) VALUES ('Trieste');
INSERT INTO City(name) VALUES ('Udine');
INSERT INTO City(name) VALUES ('Varese');
INSERT INTO City(name) VALUES ('Venezia');
INSERT INTO City(name) VALUES ('Verbano-Cusio-Ossola');
INSERT INTO City(name) VALUES ('Vercelli');
INSERT INTO City(name) VALUES ('Verona');
INSERT INTO City(name) VALUES ('Vibo Valentia');
INSERT INTO City(name) VALUES ('Vicenza');
INSERT INTO City(name) VALUES ('Viterbo');
INSERT INTO _user(id, email, password, role) VALUES ( 1000, 'gummiband', '$2a$10$hd2XdfqtnBbtRt.Otkaab.4CsdOW1p1O5X7VxRe0QL7xtxcSsF96.', 'ADMIN' );
INSERT INTO administrator( id ) VALUES ( 1000 );